/*
 * LogView.java
 *
 * Created on September 26, 2007, 1:25 PM
 */

package log_view;

/**
 *
 * @author  david
 */
public class LogView extends javax.swing.JFrame {
    
    /** Creates new form LogView */
    public LogView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        report_area = new org.jdesktop.swingx.JXTable();
        filter_wrapper_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filter_selection_panel = new filter_selection.FilterSelection();
        footer_panel = new javax.swing.JPanel();
        ok_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log Viewer");

        report_area.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Category", "Duration", "Start Time", "Billable", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        report_area.setColumnSelectionAllowed(true);
        report_area.setEditable(false);
        jScrollPane1.setViewportView(report_area);
        report_area.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        report_area.getColumnModel().getColumn(0).setPreferredWidth(300);
        report_area.getColumnModel().getColumn(3).setMinWidth(150);
        report_area.getColumnModel().getColumn(3).setMaxWidth(150);
        report_area.getColumnModel().getColumn(4).setMaxWidth(50);
        report_area.getColumnModel().getColumn(5).setMinWidth(0);
        report_area.getColumnModel().getColumn(5).setPreferredWidth(0);
        report_area.getColumnModel().getColumn(5).setMaxWidth(0);

        org.jdesktop.layout.GroupLayout log_panelLayout = new org.jdesktop.layout.GroupLayout(log_panel);
        log_panel.setLayout(log_panelLayout);
        log_panelLayout.setHorizontalGroup(
            log_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(log_panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );
        log_panelLayout.setVerticalGroup(
            log_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, log_panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
        );

        getContentPane().add(log_panel, java.awt.BorderLayout.CENTER);

        filter_wrapper_panel.setMaximumSize(null);
        filter_wrapper_panel.setMinimumSize(new java.awt.Dimension(300, 40));
        filter_wrapper_panel.setPreferredSize(new java.awt.Dimension(300, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        jLabel1.setText("Log Viewer");
        filter_wrapper_panel.add(jLabel1);
        filter_wrapper_panel.add(filter_selection_panel);

        getContentPane().add(filter_wrapper_panel, java.awt.BorderLayout.NORTH);

        footer_panel.setPreferredSize(new java.awt.Dimension(778, 46));

        ok_button.setText("Ok");
        ok_button.setMaximumSize(null);
        ok_button.setMinimumSize(null);

        org.jdesktop.layout.GroupLayout footer_panelLayout = new org.jdesktop.layout.GroupLayout(footer_panel);
        footer_panel.setLayout(footer_panelLayout);
        footer_panelLayout.setHorizontalGroup(
            footer_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, footer_panelLayout.createSequentialGroup()
                .addContainerGap(564, Short.MAX_VALUE)
                .add(ok_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        footer_panelLayout.setVerticalGroup(
            footer_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(footer_panelLayout.createSequentialGroup()
                .addContainerGap()
                .add(ok_button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(footer_panel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private filter_selection.FilterSelection filter_selection_panel;
    private javax.swing.JPanel filter_wrapper_panel;
    private javax.swing.JPanel footer_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel log_panel;
    private javax.swing.JButton ok_button;
    private org.jdesktop.swingx.JXTable report_area;
    // End of variables declaration//GEN-END:variables
    
}
