/*
 * ReportView.java
 *
 * Created on August 23, 2007, 1:36 AM
 */

package report;

import java.awt.event.ActionListener;

/**
 *
 * @author  david
 */
public class ReportForm extends javax.swing.JFrame {
    
    /** Creates new form ReportView */
    public ReportForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                checkerboardPainter1 = new org.jdesktop.swingx.painter.CheckerboardPainter();
                filter_wrapper_panel = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                filter_selection_panel = new filter_selection.FilterSelection();
                jXPanel1 = new org.jdesktop.swingx.JXPanel();
                ok_button = new javax.swing.JButton();
                export_button = new javax.swing.JButton();
                export_type_combo_box = new javax.swing.JComboBox();
                report_alignment_wrapper_panel = new javax.swing.JPanel();
                report_panel = new javax.swing.JPanel();
                report_scroll_pane = new javax.swing.JScrollPane();
                report_table = new org.jdesktop.swingx.JXTreeTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Report");

                jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24));
                jLabel2.setText("Reports");
                filter_wrapper_panel.add(jLabel2);
                filter_wrapper_panel.add(filter_selection_panel);

                getContentPane().add(filter_wrapper_panel, java.awt.BorderLayout.NORTH);

                ok_button.setText("Close");

                export_button.setText("Export");

                export_type_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSV", "XML" }));

                org.jdesktop.layout.GroupLayout jXPanel1Layout = new org.jdesktop.layout.GroupLayout(jXPanel1);
                jXPanel1.setLayout(jXPanel1Layout);
                jXPanel1Layout.setHorizontalGroup(
                        jXPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jXPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(export_type_combo_box, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(export_button)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 547, Short.MAX_VALUE)
                                .add(ok_button)
                                .addContainerGap())
                );
                jXPanel1Layout.setVerticalGroup(
                        jXPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jXPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(export_type_combo_box, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(export_button)
                                .add(ok_button))
                );

                getContentPane().add(jXPanel1, java.awt.BorderLayout.PAGE_END);

                report_panel.setLayout(new javax.swing.BoxLayout(report_panel, javax.swing.BoxLayout.LINE_AXIS));

                report_scroll_pane.setMinimumSize(null);

                report_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
                report_table.setAutoStartEditOnKeyStroke(false);
                report_table.setEditable(false);
                report_scroll_pane.setViewportView(report_table);

                report_panel.add(report_scroll_pane);

                org.jdesktop.layout.GroupLayout report_alignment_wrapper_panelLayout = new org.jdesktop.layout.GroupLayout(report_alignment_wrapper_panel);
                report_alignment_wrapper_panel.setLayout(report_alignment_wrapper_panelLayout);
                report_alignment_wrapper_panelLayout.setHorizontalGroup(
                        report_alignment_wrapper_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(0, 774, Short.MAX_VALUE)
                        .add(report_alignment_wrapper_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(report_alignment_wrapper_panelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .add(report_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                report_alignment_wrapper_panelLayout.setVerticalGroup(
                        report_alignment_wrapper_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(0, 472, Short.MAX_VALUE)
                        .add(report_alignment_wrapper_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, report_alignment_wrapper_panelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .add(report_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                                        .addContainerGap()))
                );

                getContentPane().add(report_alignment_wrapper_panel, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportForm().setVisible(true);
            }
        });
    }
    
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private org.jdesktop.swingx.painter.CheckerboardPainter checkerboardPainter1;
        private javax.swing.JButton export_button;
        private javax.swing.JComboBox export_type_combo_box;
        private filter_selection.FilterSelection filter_selection_panel;
        private javax.swing.JPanel filter_wrapper_panel;
        private javax.swing.JLabel jLabel2;
        private org.jdesktop.swingx.JXPanel jXPanel1;
        private javax.swing.JButton ok_button;
        private javax.swing.JPanel report_alignment_wrapper_panel;
        private javax.swing.JPanel report_panel;
        private javax.swing.JScrollPane report_scroll_pane;
        private org.jdesktop.swingx.JXTreeTable report_table;
        // End of variables declaration//GEN-END:variables
    
}
