/*
 * Popup.java
 *
 * Created on July 17, 2007, 11:55 AM
 */

package timelog;

import java.awt.event.KeyEvent;

/**
 *
 * @author  dkoontz
 */
public class TimeLogForm extends javax.swing.JFrame {
    
    /** Creates new form Popup */
    public TimeLogForm() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        log_time_panel = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        start_time_label = new javax.swing.JLabel();
        start_time_combo_box = new javax.swing.JComboBox();
        title2 = new javax.swing.JLabel();
        end_time_label = new javax.swing.JLabel();
        end_time_combo_box = new javax.swing.JComboBox();
        date_button = new javax.swing.JButton();
        date_picker_panel = new org.jdesktop.swingx.JXCollapsiblePane();
        start_date_picker = new org.jdesktop.swingx.JXDatePicker();
        end_date_picker = new org.jdesktop.swingx.JXDatePicker();
        log_details_panel = new org.jdesktop.swingx.JXCollapsiblePane();
        jScrollPane1 = new javax.swing.JScrollPane();
        log_details = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        details_button = new javax.swing.JButton();
        log = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        billable = new javax.swing.JCheckBox();
        category = new javax.swing.JComboBox();
        log_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Timelog entry");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);

        log_time_panel.setMinimumSize(new java.awt.Dimension(10, 38));
        log_time_panel.setPreferredSize(new java.awt.Dimension(10, 38));

        title1.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        title1.setText("From"); // NOI18N
        log_time_panel.add(title1);

        start_time_label.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        start_time_label.setText("s");
        log_time_panel.add(start_time_label);

        start_time_combo_box.setFont(start_time_combo_box.getFont().deriveFont(start_time_combo_box.getFont().getSize()+1f));
        start_time_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1:23 am" }));
        start_time_combo_box.setAutoscrolls(true);
        log_time_panel.add(start_time_combo_box);

        title2.setFont(new java.awt.Font("Lucida Grande", 0, 14));
        title2.setText("to");
        log_time_panel.add(title2);

        end_time_label.setFont(new java.awt.Font("Lucida Grande", 1, 14));
        end_time_label.setText("e");
        log_time_panel.add(end_time_label);

        end_time_combo_box.setFont(end_time_combo_box.getFont().deriveFont(end_time_combo_box.getFont().getSize()+1f));
        end_time_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12:33 pm" }));
        end_time_combo_box.setAutoscrolls(true);
        log_time_panel.add(end_time_combo_box);

        date_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        date_button.setBorderPainted(false);
        log_time_panel.add(date_button);

        date_picker_panel.setPreferredSize(new java.awt.Dimension(15, 38));
        date_picker_panel.getContentPane().setLayout(new java.awt.FlowLayout());
        date_picker_panel.getContentPane().add(start_date_picker);
        date_picker_panel.getContentPane().add(end_date_picker);

        log_details_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Log Details"));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(null);

        log_details.setColumns(20);
        log_details.setLineWrap(true);
        log_details.setRows(1);
        log_details.setWrapStyleWord(true);
        log_details.setMargin(new java.awt.Insets(0, 5, 0, 5));
        log_details.setMinimumSize(new java.awt.Dimension(210, 16));
        log_details.setPreferredSize(null);
        jScrollPane1.setViewportView(log_details);

        org.jdesktop.layout.GroupLayout log_details_panelLayout = new org.jdesktop.layout.GroupLayout(log_details_panel.getContentPane());
        log_details_panel.getContentPane().setLayout(log_details_panelLayout);
        log_details_panelLayout.setHorizontalGroup(
            log_details_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        log_details_panelLayout.setVerticalGroup(
            log_details_panelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );

        details_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil_2.png"))); // NOI18N
        details_button.setBorderPainted(false);

        log.setEditable(true);
        log.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Worked on..." }));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(log, 0, 342, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(details_button)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(details_button)
                    .add(log, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        billable.setText("Billable?"); // NOI18N
        billable.setMargin(new java.awt.Insets(0, 0, 0, 10));

        category.setEditable(true);
        category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Work", "Personal", "Miscellaneous" }));
        category.setOpaque(true);

        log_button.setMnemonic(KeyEvent.VK_ENTER);
        log_button.setText("Log"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(billable)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(category, 0, 197, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(log_button)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(category, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(billable)
                    .add(log_button)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(date_picker_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .add(log_time_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(log_details_panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(log_time_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(date_picker_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(log_details_panel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox billable;
    private javax.swing.JComboBox category;
    private javax.swing.JButton date_button;
    private org.jdesktop.swingx.JXCollapsiblePane date_picker_panel;
    private javax.swing.JButton details_button;
    private org.jdesktop.swingx.JXDatePicker end_date_picker;
    private javax.swing.JComboBox end_time_combo_box;
    private javax.swing.JLabel end_time_label;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox log;
    private javax.swing.JButton log_button;
    private javax.swing.JTextArea log_details;
    private org.jdesktop.swingx.JXCollapsiblePane log_details_panel;
    private javax.swing.JPanel log_time_panel;
    private org.jdesktop.swingx.JXDatePicker start_date_picker;
    private javax.swing.JComboBox start_time_combo_box;
    private javax.swing.JLabel start_time_label;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
    
}
