
/*
 * FilterSelection.java
 *
 * Created on August 8, 2008, 4:31 PM
 */

package filter_selection;

/**
 *
 * @author  david
 */
public class FilterSelection extends javax.swing.JPanel {

    /** Creates new form FilterSelection */
    public FilterSelection() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selected_report_combo_box = new javax.swing.JComboBox();
        spacer = new javax.swing.JLabel();
        edit_button = new javax.swing.JButton();
        add_label = new javax.swing.JLabel();

        selected_report_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Today", "Yesterday", "This Week", "This Month", "This Year", "<Add a new report>" }));
        add(selected_report_combo_box);

        spacer.setText("   ");
        add(spacer);

        edit_button.setText("Edit");
        add(edit_button);

        add_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        add(add_label);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_label;
    private javax.swing.JButton edit_button;
    private javax.swing.JComboBox selected_report_combo_box;
    private javax.swing.JLabel spacer;
    // End of variables declaration//GEN-END:variables

}
