/*
 * LicenseKey.java
 *
 * Created on June 16, 2008, 8:42 PM
 */

package license_key;

/**
 *
 * @author  james
 */
public class LicenseKey extends javax.swing.JFrame {

    /** Creates new form LicenseKey */
    public LicenseKey() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        license_key_text = new javax.swing.JEditorPane();
        ok_button = new javax.swing.JButton();
        body_label = new javax.swing.JLabel();
        status_label = new javax.swing.JLabel();
        info_label01 = new javax.swing.JLabel();
        trial_link_label = new javax.swing.JLabel();
        info_lable02 = new javax.swing.JLabel();
        buy_link_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter your license key");
        setResizable(false);

        jScrollPane2.setViewportView(license_key_text);

        ok_button.setText("OK");

        body_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        body_label.setText("<html>Please copy and paste the license key E-mailed to you when either requesting a trial key or when purchasing JotBot<br><br>  If you did not recieve your key or if you need to request your key again, please email support@getjotbot.com</html> ");

        status_label.setText("You should never see this");

        info_label01.setText("To obtain a 30-day trial key, click here:");

        trial_link_label.setText("<html><a href='http://www.getjotbot.com/ks/trial'>http://www.getjotbot.com/ks/trial</a></html>");

        info_lable02.setText("To purchase JotBot, click here: ");

        buy_link_label.setText("<html><a href='http://www.getjotbot.com/buy'>http://www.getjotbot.com/buy</a></html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, body_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(status_label, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(ok_button))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(info_label01)
                        .add(18, 18, 18)
                        .add(trial_link_label))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(info_lable02)
                        .add(18, 18, 18)
                        .add(buy_link_label)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(info_label01)
                    .add(trial_link_label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(info_lable02)
                    .add(buy_link_label))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(body_label, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ok_button)
                    .add(status_label))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LicenseKey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel body_label;
    private javax.swing.JLabel buy_link_label;
    private javax.swing.JLabel info_label01;
    private javax.swing.JLabel info_lable02;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane license_key_text;
    private javax.swing.JButton ok_button;
    private javax.swing.JLabel status_label;
    private javax.swing.JLabel trial_link_label;
    // End of variables declaration//GEN-END:variables

}
