/*
 * ReportEditorRow.java
 *
 * Created on July 24, 2008, 1:04 PM
 */

package report_editor_row;

/**
 *
 * @author  david
 */
public class ReportEditorRow extends javax.swing.JPanel {

    /** Creates new form ReportEditorRow */
    public ReportEditorRow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type_combo_box = new javax.swing.JComboBox();
        specifier_combo_box = new javax.swing.JComboBox();
        parameter_text_field = new javax.swing.JTextField();
        qualifier_label = new javax.swing.JLabel();
        date_picker = new org.jdesktop.swingx.JXDatePicker();
        delete_label = new javax.swing.JLabel();
        add_label = new javax.swing.JLabel();

        setLayout(null);

        type_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Date", "Category", "Billable" }));
        add(type_combo_box);
        type_combo_box.setBounds(0, 0, 107, 27);

        specifier_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "is equal to", "is less than", "is greater than", "is within" }));
        add(specifier_combo_box);
        specifier_combo_box.setBounds(110, 0, 142, 27);
        add(parameter_text_field);
        parameter_text_field.setBounds(250, 0, 90, 28);

        qualifier_label.setText("days");
        add(qualifier_label);
        qualifier_label.setBounds(348, 6, 50, 16);
        add(date_picker);
        date_picker.setBounds(250, 0, 151, 28);

        delete_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/subtract.png"))); // NOI18N
        add(delete_label);
        delete_label.setBounds(400, 10, 16, 16);

        add_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        add(add_label);
        add_label.setBounds(420, 10, 16, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_label;
    private org.jdesktop.swingx.JXDatePicker date_picker;
    private javax.swing.JLabel delete_label;
    private javax.swing.JTextField parameter_text_field;
    private javax.swing.JLabel qualifier_label;
    private javax.swing.JComboBox specifier_combo_box;
    private javax.swing.JComboBox type_combo_box;
    // End of variables declaration//GEN-END:variables

}
