/*
 * CategoryEditor.java
 *
 * Created on June 6, 2008, 12:30 AM
 */

package category_editor;

/**
 *
 * @author  david
 */
public class CategoryEditor extends javax.swing.JFrame {

    /** Creates new form CategoryEditor */
    public CategoryEditor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                selected_category_id = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                category_list = new javax.swing.JList();
                selected_category_text_field = new javax.swing.JTextField();
                save_button = new javax.swing.JButton();
                new_button = new javax.swing.JButton();
                billable = new javax.swing.JCheckBox();
                active = new javax.swing.JCheckBox();

                selected_category_id.setText("0");

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Category Editor");

                category_list.setModel(new javax.swing.AbstractListModel() {
                        String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
                        public int getSize() { return strings.length; }
                        public Object getElementAt(int i) { return strings[i]; }
                });
                category_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
                category_list.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
                jScrollPane1.setViewportView(category_list);

                selected_category_text_field.setText("jTextField1");
                selected_category_text_field.setName("selected_category_text_field"); // NOI18N
                selected_category_text_field.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selected_category_text_fieldActionPerformed(evt);
                        }
                });

                save_button.setText("Save");

                new_button.setText("New");

                billable.setText("Billable");

                active.setText("Active");

                org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1)
                                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                                .add(selected_category_text_field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(billable)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(active)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(save_button)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(new_button)))
                                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                                .addContainerGap()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                        .add(billable)
                                        .add(active)
                                        .add(save_button)
                                        .add(new_button)
                                        .add(selected_category_text_field, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

		private void selected_category_text_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selected_category_text_fieldActionPerformed
			// TODO add your handling code here:
		}//GEN-LAST:event_selected_category_text_fieldActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryEditor().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JCheckBox active;
        private javax.swing.JCheckBox billable;
        private javax.swing.JList category_list;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JButton new_button;
        private javax.swing.JButton save_button;
        private javax.swing.JLabel selected_category_id;
        private javax.swing.JTextField selected_category_text_field;
        // End of variables declaration//GEN-END:variables

}
