/*
 * SplashScreen.java
 *
 * Created on August 13, 2008, 6:01 PM
 */

package splash_screen;

/**
 *
 * @author  david
 */
public class SplashScreen extends javax.swing.JFrame {

    /** Creates new form SplashScreen */
    public SplashScreen() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        version_label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        status_message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JotBot loading...");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JotBot");
        jLabel1.setMinimumSize(new java.awt.Dimension(235, 58));
        jLabel1.setPreferredSize(new java.awt.Dimension(235, 58));
        getContentPane().add(jLabel1);

        version_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        version_label.setText("Version: ");
        getContentPane().add(version_label);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/spinner.gif"))); // NOI18N
        getContentPane().add(jLabel2);

        status_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status_message.setText("Status");
        getContentPane().add(status_message);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel status_message;
    private javax.swing.JLabel version_label;
    // End of variables declaration//GEN-END:variables

}
